events {}
http {
    server {
        listen 80;
        server_name 46.250.234.91.sslip.io;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "nginx is up";
        }
    }
}